Implement BAM format inputs
hallamlab/FabFos pull request #2
Opened 2019-12-12 21:37 UTC by kshitij3579

Added a bam2fastq function. BAM inputs should work and backbone filtering was done using this function.

2019-12-13 22:14 UTC, cmorganl requested changes
This branch will be merged to main once the requested changes have been made. Overall, looks like it should work and is a useful addition to the tool.

2019-12-13 22:14 UTC, cmorganl commented on FabFos.py
> +    p_bam2fastq = subprocess.Popen(' '.join(fastq_extract), shell=True, preexec_fn=os.setsid)
Setting the `shell` parameter to `True` is a security issue and though this probably won't be critical to FabFos, it is frowned upon. Instead, I suggest removing the `' '.join()` call and setting `shell` to False.

2019-12-13 22:14 UTC, cmorganl commented on FabFos.py
> +                     output_dir + os.sep + sample_id + input_file + ".fasta", "--no-aligned", input_file]
Typo in output path name - these should be ".fastq" not ".fasta". Also, let's use `_#` in the path in the same string as ".fastq" - `bam2fsatq` uses this to specify the forward and reverse reads.

2019-12-13 22:14 UTC, cmorganl commented on FabFos.py
> +                                                 "NOTE: a maximum of 2 sequence files are permitted.",add_help=False)
This can be changed back to the original version.

2019-12-13 22:14 UTC, cmorganl commented on FabFos.py
> +                      help="Enter B if input type is BAM, F for FastQ")
Always a good idea to leave a note with what the default value is e.g. [ DEFAULT = 'F' ]

2019-12-13 22:14 UTC, cmorganl commented on FabFos.py
> +
This code should come outside of the `get_options` function. I suggest immediately after the call to `get_options` in the main function of FabFos.

2019-12-16 20:03 UTC, kshitij3579 commented
I've made all the requested changes. Should I now submit another pull request?

2019-12-17 21:28 UTC, cmorganl approved these changes

2019-12-17 21:29 UTC, merged